name: Lint

on:
  workflow_call:   # 👈 makes it reusable
    inputs:
      node-version:
        required: false
        default: '18'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
